services:
  frontend:
    build:
      context: .
      target: dev
    working_dir: /app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      API_INTERNAL_URL: ${API_INTERNAL_URL:-http://host.docker.internal:8000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - frontend_node_modules_dev:/app/node_modules

volumes:
  frontend_node_modules_dev:
