services:
  frontend:
    build:
      context: .
      target: dev
    working_dir: /app
    command: yarn dev
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - frontend_node_modules_dev:/app/node_modules

volumes:
  frontend_node_modules_dev:
