import type { FavoritesResponse } from "../types";

export const fallbackFavorites: FavoritesResponse = {
  items: [],
  total: 0,
  page: 1,
  limit: 100,
  pages: 0,
};

export const fallbackProfileFavorites: FavoritesResponse = {
  items: [
    {
      id: 101,
      name: "Бананы",
      slug: "banany",
      price: "99",
      unit: "1 кг",
      product_type: "weighted",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 102,
      name: "Молоко Простоквашино 2,5%",
      slug: "moloko-prostokvashino-25",
      price: "89",
      unit: "930 мл",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 103,
      name: "Хлеб Бородинский",
      slug: "hleb-borodinskiy",
      price: "49",
      unit: "400 г",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 104,
      name: "Сыр Российский",
      slug: "syr-rossiyskiy",
      price: "199",
      unit: "200 г",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 105,
      name: "Томаты сливовидные",
      slug: "tomaty-slivovidnye",
      price: "129",
      unit: "500 г",
      product_type: "weighted",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 106,
      name: "Филе куриное",
      slug: "file-kurinoe",
      price: "349",
      unit: "охлажденное, 1 кг",
      product_type: "weighted",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 107,
      name: "Огурцы среднеплодные",
      slug: "ogurcy-sredneplodnye",
      price: "119",
      unit: "600 г",
      product_type: "weighted",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 108,
      name: "Авокадо Хасс",
      slug: "avokado-hass",
      price: "129",
      unit: "1 шт.",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 109,
      name: "Хлопья овсяные",
      slug: "hlopya-ovsyanye",
      price: "79",
      unit: "500 г",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 110,
      name: "Шоколад Alpen Gold",
      slug: "shokolad-alpen-gold",
      price: "69",
      unit: "молочный, 90 г",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 111,
      name: "Кофе Nescafe Gold",
      slug: "kofe-nescafe-gold",
      price: "399",
      unit: "растворимый, 95 г",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
    {
      id: 112,
      name: "Гель для стирки Persil",
      slug: "gel-dlya-stirki-persil",
      price: "599",
      unit: "1,3 л",
      product_type: "piece",
      is_available: true,
      stock_display: "В наличии",
    },
  ],
  total: 12,
  page: 1,
  limit: 100,
  pages: 1,
};
