import type {
  ProductDiscountedResponse,
  ProductListResponse,
  ProductNewResponse,
  ProductPopularResponse,
  ProductShortResponse,
} from "../types";

const fallbackItems: ProductShortResponse[] = [
  {
    id: 1,
    name: "Яблоки Гала",
    slug: "yabloki-gala",
    price: "129",
    old_price: "152",
    discount_percent: 15,
    unit: "1 кг",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 2,
    name: "Бананы",
    slug: "banany",
    price: "89",
    unit: "1 кг",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 3,
    name: "Клубника",
    slug: "klubnika",
    price: "199",
    unit: "250 г",
    product_type: "weight",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 4,
    name: "Апельсины",
    slug: "apelsiny",
    price: "119",
    old_price: "149",
    discount_percent: 20,
    unit: "1 кг",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 5,
    name: "Голубика",
    slug: "golubika",
    price: "169",
    old_price: "199",
    discount_percent: 15,
    unit: "125 г",
    product_type: "weight",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 6,
    name: "Авокадо Хасс",
    slug: "avokado-hass",
    price: "149",
    unit: "1 шт.",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 7,
    name: "Мандарины",
    slug: "mandariny",
    price: "99",
    old_price: "109",
    discount_percent: 10,
    unit: "1 кг",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 8,
    name: "Малина",
    slug: "malina",
    price: "199",
    unit: "125 г",
    product_type: "weight",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 9,
    name: "Томаты сливовидные",
    slug: "tomaty-slivovidnye",
    price: "199",
    unit: "1 кг",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 10,
    name: "Огурцы длинные",
    slug: "ogurtsy-dlinnye",
    price: "149",
    unit: "1 кг",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 11,
    name: "Молоко Домик в деревне",
    slug: "moloko-domik-v-derevne",
    price: "79",
    unit: "2,5%, 900 мл",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 12,
    name: "Сыр Российский",
    slug: "syr-rossiyskiy",
    price: "79",
    old_price: "99",
    discount_percent: 15,
    unit: "100 г",
    product_type: "weight",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 13,
    name: "Хлеб Бородинский",
    slug: "hleb-borodinskiy",
    price: "49",
    unit: "400 г",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 14,
    name: "Сок Добрый Апельсин",
    slug: "sok-dobryy-apelsin",
    price: "89",
    old_price: "119",
    discount_percent: 20,
    unit: "1 л",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 15,
    name: "Яйцо куриное C1",
    slug: "yaytso-kurinoe-c1",
    price: "89",
    old_price: "129",
    discount_percent: 25,
    unit: "10 шт.",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 16,
    name: "Йогурт Epica",
    slug: "yogurt-epica",
    price: "59",
    unit: "клубника-киви, 130 г",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 17,
    name: "Творог Простоквашино",
    slug: "tvorog-prostokvashino",
    price: "119",
    unit: "5%, 200 г",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 18,
    name: "Масло сливочное",
    slug: "maslo-slivochnoe",
    price: "119",
    old_price: "141",
    discount_percent: 15,
    unit: "82,5%, 180 г",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 19,
    name: "Хлебцы Щедрые",
    slug: "hlebtsy-schedrye",
    price: "69",
    unit: "гречневые, 100 г",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
  {
    id: 20,
    name: "Вода Святой Источник",
    slug: "voda-svyatoy-istochnik",
    price: "39",
    unit: "негазированная, 1,5 л",
    product_type: "piece",
    is_available: true,
    stock_display: "В наличии",
  },
];

export const fallbackCatalogProducts: ProductListResponse = {
  items: fallbackItems,
  total: 582,
  page: 1,
  limit: 24,
  pages: 25,
};

export const fallbackPopularProducts: ProductPopularResponse = {
  items: fallbackItems,
  total: fallbackItems.length,
};

export const fallbackDiscountedProducts: ProductDiscountedResponse = {
  items: fallbackItems.filter((item) => item.discount_percent),
  total: fallbackItems.filter((item) => item.discount_percent).length,
  page: 1,
  limit: 8,
  pages: 1,
};

export const fallbackNewProducts: ProductNewResponse = {
  items: fallbackItems.slice().reverse(),
  total: fallbackItems.length,
};
