export const ROUTES = {
  HOME: "/",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_LOGIN: "/admin/login",
  CATALOG: "/catalog",
  CATEGORY: (slug: string): string => `/catalog/${slug}`,
  PRODUCT: (slug: string): string => `/product/${slug}`,
  SEARCH: "/search",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  FAVORITES: "/profile/favorites",
  FORGOT_PASSWORD: "/forgot-password",
  LOGIN: "/login",
  PROFILE: "/profile",
  PROFILE_ADDRESSES: "/profile/addresses",
  PROFILE_CHANGE_PASSWORD: "/profile/change-password",
  PROFILE_FAVORITES: "/profile/favorites",
  PROFILE_NOTIFICATIONS: "/profile/notifications",
  PROFILE_ORDER: (orderId: number | string): string => `/profile/orders/${orderId}`,
  PROFILE_ORDERS: "/profile/orders",
  PROFILE_UPLOADS: "/profile/uploads",
  REGISTER: "/register",
  RESET_PASSWORD: "/reset-password",
} as const;
