export const ROUTES = {
  HOME: "/",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_DELIVERY: "/admin/delivery",
  ADMIN_DISCOUNTS: "/admin/discounts",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_NOTIFICATIONS: "/admin/notifications",
  ADMIN_ORDER: (orderId: number | string): string => `/admin/orders/${orderId}`,
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_PRODUCT_CREATE: "/admin/products/create",
  ADMIN_PRODUCT_EDIT: (productId: number | string): string => `/admin/products/${productId}`,
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_PROMO_CODES: "/admin/promo-codes",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_STAFF: "/admin/staff",
  CATALOG: "/catalog",
  CATEGORY: (slug: string): string => `/catalog/${slug}`,
  PRODUCT: (slug: string): string => `/product/${slug}`,
  SEARCH: "/search",
  CART: "/cart",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  FAVORITES: "/profile/favorites",
  FORGOT_PASSWORD: "/forgot-password",
  LOGIN: "/login",
  PROFILE: "/profile",
  PROFILE_ADDRESSES: "/profile/addresses",
  PROFILE_CHANGE_PASSWORD: "/profile/change-password",
  PROFILE_FAVORITES: "/profile/favorites",
  PROFILE_NOTIFICATIONS: "/profile/notifications",
  PROFILE_ORDER: (orderId: number | string): string => `/profile/orders/${orderId}`,
  PROFILE_ORDERS: "/profile/orders",
  PROFILE_UPLOADS: "/profile/uploads",
  REGISTER: "/register",
  RESET_PASSWORD: "/reset-password",
} as const;
